### ISSUE TITLE
首先很感谢你能整理出这个新的pykylin，但是我用了这个和原版的那一个遇到了同样的问题。

### ISSUE THREAD

**Issue by lsasta** [ciwei100000/pykylin#1]
当我使用的project是kylin自带的那一个时，我能连接上。但是当使用我自己的project的时候就报错。
![image](https://user-images.githubusercontent.com/27410399/31044390-fdac20c8-a600-11e7-9b64-bf702cf0c00d.png)
superset的日志是
2017-09-30 17:01:08,527:ERROR:root:(pykylin.errors.Error) Login failed with username: "ADMIN"
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/views/core.py", line 1396, in testconn
    engine.connect()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2091, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2177, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 1045, in _do_get
    c = self._create_connection()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/pykylin-0.0.1-py2.7.egg/pykylin/connection.py", line 53, in connect
    return Connection(username, password, endpoint, project, **kwargs)
  File "/usr/lib/python2.7/site-packages/pykylin-0.0.1-py2.7.egg/pykylin/connection.py", line 17, in __init__
    self.proxy.login(self.username, self.password)
  File "/usr/lib/python2.7/site-packages/pykylin-0.0.1-py2.7.egg/pykylin/proxy.py", line 29, in login
    raise Error('Login failed with username: "%s"' % self.user)
DBAPIError: (pykylin.errors.Error) Login failed with username: "ADMIN"
不知道你们其他人遇到过这个问题没有。
烦请指教！！！
谢谢

**Comment by ciwei100000** [comment]
这个错误我还没遇到过，我们本身都是自己建的Project，kylin没有自带Project。能看看你的SQLAlchemy的URL吗？感觉像是Project名字写错了或者是没有权限。

**Comment by derek-zl** [comment]
这个第三方库还在维护吗？
